In [4]:
!pip3 install numpy

    100% |████████████████████████████████| 24.5MB 1.9MB/s  eta 0:00:01


In [5]:
import numpy

In [6]:
numpy.__version__

'1.15.4'

In [7]:
import numpy as np

In [8]:
result = 0
for i in range(100):
    result += i
# in other languages like C, have to explicitly cast
# Python dynamically infers type 
# really fast / convenient, but costs storing extra information

In [9]:
print(result)

4950


In [10]:
x = 4
print(type(x))

<class 'int'>


In [11]:
x = 'String now?'
print(type(x))

<class 'str'>


In [12]:
# single integer in python contains ob_refcnt: reference count that helps Python manage memory allocation / deallocation
# ob_type: encodes the type of the variable
# ob_size: specifies the size of the following data members
# ob_digit: contains actual integer value we expect Python variable to represent

In [13]:
L = list(range(10))

In [14]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
type(L[0])

int

In [16]:
L2 = [str(c) for c in L]

In [17]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
type(L2[0])

str

In [20]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
# list is not just a list
# each item in list must contain its own type info
# each item is a complete python object
# much more efficient to store data in fixed-type array if all variables are same type
# implementation: Python list is pointer to block of pointers --> pointing to full python objects (very flexible but costly)
# array on other hand is single pointer to one contiguous block of data

In [23]:
import array
L = list(range(10))
A = array.array('i', L)
A
# i in this case is type code indicating contents are integers
# array offers efficient operations

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
np.array([1.,2,3,4.5])
# converts everything to same type if possible (in this case a float)

array([1. , 2. , 3. , 4.5])

In [26]:
np.array([1,2,3,4,5], dtype='float32')
# can explicitly cast as float

array([1., 2., 3., 4., 5.], dtype=float32)

In [27]:
np.array([range(i, i+3) for i in [2, 4,6]])
# can create multi dimensional arrays

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
np.array([range(i,i+4) for i in range(3)])

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [30]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [35]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.linspace(0,1,5)
# creates 5 evenly spaced segments - equivalent of 1 / 4 to determine gap

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.random.random((3,5))

array([[0.84052549, 0.44142225, 0.40131189, 0.38399866, 0.86387066],
       [0.69759713, 0.4014843 , 0.25223089, 0.54511406, 0.18492331],
       [0.79906738, 0.63822536, 0.33559939, 0.69584797, 0.7866296 ]])

In [39]:
np.random.normal(0,1,(3,5))
# drawing from normally distributed random values with mean = 0, and std = 1

array([[ 2.54878026, -0.01838279,  0.47408121,  0.50830208,  0.69081145],
       [-0.34987519,  1.39595536, -0.91896513, -1.3115537 ,  0.32715107],
       [-0.23642028,  0.54138933, -1.91197318, -1.0253234 ,  0.82724527]])

In [40]:
np.random.randint(0,10,(3,5))

array([[3, 0, 2, 4, 5],
       [8, 4, 6, 9, 1],
       [2, 2, 3, 5, 7]])

In [52]:
np.eye(3)
# identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.empty(3)
# unititialized array of three integers (values will be whatever is already there)

array([1., 1., 1.])

In [54]:
# bool_
# int_, intc, intp, int8, int16, int32, int64 --> -xyz to xyz-1 (ex. -128 to 127, -32768 to 32767, etc.)
# uint8, uint16, uint32, uint64 --> 0 to xyz
# float_, float16, float32, float64
# complex_, complex64, complex128

In [55]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [58]:
print("x3 ndim: ", x3.ndim) # dimensions
print("x3 shape: ", x3.shape) # row x column x etc
print("x3 size: ", x3.size) # total number of entries (row * col * etc.)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [59]:
print("dtype: ", x3.dtype)

dtype:  int64


In [60]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


In [61]:
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
x1[0]

5

In [63]:
x1[4]

7

In [64]:
x1[-1]

9

In [65]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [66]:
x2[0,0]

3

In [67]:
x2[2,0]

1

In [68]:
x = np.arange(10)

In [69]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[0:6:2]

array([0, 2, 4])

In [71]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x[5:]

array([5, 6, 7, 8, 9])

In [73]:
x[4:7]

array([4, 5, 6])

In [74]:
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
x[::-1] # reverses list

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
x[5::-2] # reverse list from 5 and select every other

array([5, 3, 1])

In [81]:
x2 = np.random.randint(10, size=(2,3))

In [82]:
x2

array([[2, 0, 7],
       [5, 9, 0]])

In [83]:
x2[:, ::2]

array([[2, 7],
       [5, 0]])

In [84]:
x2[::-1, ::-1]

array([[0, 9, 5],
       [7, 0, 2]])

In [85]:
print(x2[:, 0])

[2 5]


In [86]:
print(x2[1]) # defaults to row access

[5 9 0]


In [90]:
x2 = np.random.randint(10,size=(3,4))

array([[2, 7, 2, 9],
       [2, 3, 3, 2],
       [3, 4, 1, 2]])

In [92]:
x2_sub = x2[:2,:2]

In [93]:
print(x2_sub)

[[2 0]
 [5 9]]


In [94]:
x2_sub[0,0] = 99
# x2_sub created a view, not a copy of the original array
# can be very useful - can work with large data sets, then access and process pieces of datasets

In [95]:
print(x2_sub)

[[99  0]
 [ 5  9]]


In [96]:
print(x2)

[[99  0  7]
 [ 5  9  0]]


In [97]:
x2_sub_copy = x2[:2, :2].copy()
# creates actual copy

In [98]:
x2_sub_copy[0,1] = 1000

In [99]:
print(x2_sub_copy)

[[  99 1000]
 [   5    9]]


In [100]:
print(x2)

[[99  0  7]
 [ 5  9  0]]


In [103]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
x = np.array([1,2,3])

In [109]:
print(x.shape)

(3,)


In [105]:
x.reshape((1,3))

array([[1, 2, 3]])

In [107]:
x[np.newaxis, :] 
# equivalent to reshaping - adding single row

array([[1, 2, 3]])

In [110]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [112]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [113]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [115]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [116]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [117]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [118]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [121]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],
                 [7,8,9]])
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
y = np.array([[1],
              [2]])
np.hstack([grid,y])

array([[4, 5, 6, 1],
       [7, 8, 9, 2]])

In [127]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)
# number of distinct segments = number of break points + 1

[1 2 3] [4 5] [6 7 8]


In [129]:
grid = np.arange(25).reshape((5,5))
print(grid)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [133]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [134]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [135]:
# use np.dsplit to split arrays across third dimension

In [137]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [140]:
big_array = np.random.randint(1,10,size=1000000)
%timeit compute_reciprocals(big_array)
# takes several seconds to run - very slow (though pretty typical implementation for C / other languages)

1.62 s ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [142]:
print(compute_reciprocals(values))
print(1.0/values)
%timeit (1.0/big_array)
# UFuncs are for statically typed, compiled routine - called vectorized operations (much faster!)
# main purpose is to quickly execute repeated operations on values in NumPy arrays
# very flexible - works btw scalar and array, btw array and array, etc.

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]
1.46 ms ± 5.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [144]:
np.arange(5) / np.arange(1,6) 
# 0/1, 1/2, 2/3, ...

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [145]:
x = np.arange(9).reshape((3,3))
2 ** x
# not limited to one dimensional array

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [149]:
x = np.arange(4)
print("x + 5 = ", x+5) # np.add
print("x - 2 = ", x-2) # np.substract
print("x * 2 = ", x*2) # np.multiply
print("x / 2 = ", x/2) # np.divide
print("x // 2 = ", x//2) # np.floor_divide
print("-x = ", -x) # np.negative
print("x ** 2 = ", x**2)# np.power
print("x % 2 = ", x%2) # np.mod

print("-(x*0.5 + 1) ** 2 = ", -(x*0.5+1) ** 2)

x + 5 =  [5 6 7 8]
x - 2 =  [-2 -1  0  1]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
-(x*0.5 + 1) ** 2 =  [-1.   -2.25 -4.   -6.25]


In [150]:
np.add(x,2)

array([2, 3, 4, 5])

In [152]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
abs(x)
np.absolute(x)

array([3, 2, 1, 0, 1, 2, 3])

In [153]:
x = np.array([3-4j, 4-3j, 2 + 0j, 0 + 1j])
np.abs(x)
# absolute value returns magnitude of complex numbers

array([5., 5., 2., 1.])

In [158]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [157]:
x = [-1, 0, 1]
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [159]:
x = [1,2,3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [160]:
x = [1, 2, 4, 10]
print("x = ", x)
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [161]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1", np.expm1(x))
print("log(1+x) = ", np.log1p(x))
# when x is small, these functions give more precise vlaues

exp(x) - 1 [0.         0.0010005  0.01005017 0.10517092]
log(1+x) =  [0.         0.0009995  0.00995033 0.09531018]


In [162]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)
# can specifcy output using functions - more efficient memory use (no temp array)

[ 0. 10. 20. 30. 40.]


In [167]:
x = np.arange(1,6)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))
# np.sum, np.prod, np.cumsum, np.cumprod functions exist also

[1 2 3 4 5]
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [168]:
x = np.arange(1,6)
np.multiply.outer(x,x)
# can compute output of all pairs of two different inputs - can create multiplication table for example

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [171]:
import numpy as np

L = np.random.random(100)
print(sum(L))
print(np.sum(L))

big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

# same result, but np.sum is much more performant (sum and np.sum not equal) - 5x as fast in this case

51.91398886347334
51.91398886347334
67.4 ms ± 163 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
290 µs ± 8.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [172]:
big_array = np.random.rand(1000000)
%timeit min(big_array)
%timeit np.min(big_array)

print(big_array.min())
print(big_array.max())
print(big_array.sum())



51.2 ms ± 465 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
316 µs ± 8.16 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.890489775835391e-07
0.9999993031657582
499790.2976229209
